services:
  # app:
  #   build: .
  #   ports:
  #     - '9000:9000'
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     redis:
  #       condition: service_started
  #   volumes:
  #     - ./src:/usr/src/app/src
  #   restart: on-failure

  db:
    container_name: app-db
    image: postgres:16
    ports:
      - '5555:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGUSER: postgres
      POSTGRES_DB: luft
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    container_name: app-redis
    image: redis:alpine
    ports:
      - '6379:6379'
