name: CI
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:20.11-alpine

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: luft

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5555:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run lint check
        run: yarn lint

      - name: Run database migrations
        run: yarn db:migrate

      - name: Run all tests
        run: yarn test
        env:
          DATABASE_URL: 'postgres://postgres:postgres@localhost:5555/luft'
