name: CI
on: push

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    container: node:20.11-alpine

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run lint check
        run: yarn lint

      - name: Run all tests
        run: yarn test

env:
  POSTGRES_URL: 'postgres://postgres:postgres@postgres:5555/luft'
  REDIS_URL: 'redis://redis:6379'
